apiVersion: v1
kind: Template
metadata:
  name: manageiq-template
  annotations:
    description: Containerized manageiq
  creationTimestamp: null
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: docker-manageiq
      name: docker-manageiq
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      creationTimestamp: null
      labels:
        app: docker-manageiq
      name: docker-manageiq
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: docker-manageiq:latest
      resources: {}
      source:
        git:
          ref: openshift
          uri: https://github.com/vrutkovs/docker-manageiq.git
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: DockerImage
            name: library/centos:7
        type: Docker
      triggers:
      - github:
          secret: secret101
        type: GitHub
      - generic:
          secret: secret101
        type: Generic
      - type: ConfigChange
    status:
      lastVersion: 0
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      annotations:
        openshift.io/scc: privileged
      creationTimestamp: null
      labels:
        app: docker-manageiq
      name: docker-manageiq-master
    spec:
      replicas: 1
      selector:
        app: docker-manageiq
        deploymentconfig: docker-manageiq-master
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Recreate
      template:
        metadata:
          annotations:
            openshift.io/scc: privileged
          creationTimestamp: null
          labels:
            app: docker-manageiq
            deploymentconfig: docker-manageiq-master
        spec:
          containers:
          - image: docker-manageiq:latest
            imagePullPolicy: Always
            name: docker-manageiq-master
            ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 5432
              protocol: TCP
            resources: {}
            securityContext:
              privileged: true
              runAsUser: 0
            terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext:
            privileged: true
            runAsUser: 0
          terminationGracePeriodSeconds: 30
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - docker-manageiq-master
          from:
            kind: ImageStreamTag
            name: docker-manageiq:latest
        type: ImageChange
  - kind: Route
    apiVersion: v1
    metadata:
      labels:
        app: docker-manageiq
      name: manageiq-route
    spec:
      port:
        targetPort: "3000"
      tls:
        termination: passthrough
      to:
        kind: Service
        name: manageiq-web
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: docker-manageiq
      name: www
    spec:
      ports:
      - name: http
        port: 3000
        protocol: TCP
        targetPort: 3000
      selector:
        app: docker-manageiq
      sessionAffinity: None
      type: ClusterIP
